#!/bin/sh

\clear

install_skel(){
	if [ $(whoami) = "root" ];
	then
		mv /etc/skel /etc/skel.old || mkdir -p /etc/skel
		cp -r homedir/ /etc/skel/.
	else
		sudo mv /etc/skel /etc/skel.old || sudo mkdir -p /etc/skel
		sudo cp -r ./homedir/ /etc/skel/.
	fi
}

install_home(){
	for i in `find ./homedir/.config/`; do
		rm -rf ~/.config/$i
	done

	for i in `find ./homedir`; do
		cp -r $i ~/.
	done
}


printf "\033[1;92mWoof's Configuration Installer\033[0m\n"
read -p "Do you want to install the configurations for the current user? [y/n] ": yn
case $yn in 
	[Yy]* ) install_home; install_skel;;
	[Nn]* ) install_skel;;
esac
